decoration {
    rounding = 10

    # Configuración de Sombras (Nueva Sintaxis)
    shadow {
        enabled = true
        range = 4
        render_power = 3
        color = rgba(1a1a1aee)
    }

    # Configuración de Blur (Desenfoque)
    blur {
        enabled = true
        size = 8
        passes = 3
        new_optimizations = true
        xray = true
        
        # El overlay oscuro que querías para ver bien las letras
        brightness = 0.8
        contrast = 1.0
        noise = 0.01
    }
}
