# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(20191D)
$foreground = rgb(CCCEF1)
$color0 = rgb(473F44)
$color1 = rgb(241028)
$color2 = rgb(221130)
$color3 = rgb(14217E)
$color4 = rgb(0D29A5)
$color5 = rgb(0D29A5)
$color6 = rgb(5257A1)
$color7 = rgb(ADB1E3)
$color8 = rgb(797C9F)
$color9 = rgb(301536)
$color10 = rgb(2E1740)
$color11 = rgb(1B2CA8)
$color12 = rgb(1137DC)
$color13 = rgb(1137DC)
$color14 = rgb(6D74D7)
$color15 = rgb(ADB1E3)
