# always refer to Hyprland wiki
# https://wiki.hyprland.org/

# Initial boot script enable to apply initial wallpapers, theming, new settings etc.
# suggest not to change this or delete this including deleting referrence file in ~/.config/hypr/.initial_startup_done
# as long as the referrence file is present, this initial-boot.sh will not execute
exec-once = $HOME/.config/hypr/initial-boot.sh

# Sourcing external config files
$configs = $HOME/.config/hypr/configs # Default Configs directory path

source=$configs/Keybinds.conf # Pre-configured keybinds

# ## This is where you want to start tinkering 
$UserConfigs = $HOME/.config/hypr/UserConfigs # User Configs directory path

source= $UserConfigs/Startup_Apps.conf # put your start-up packages on this file

source= $UserConfigs/ENVariables.conf # Environment variables to load

#source= $UserConfigs/Monitors.conf # Its all about your monitor config (old dots) will remove on push to main
#source= $UserConfigs/WorkspaceRules.conf # Hyprland workspaces (old dots) will remove on push to main

source= $UserConfigs/Laptops.conf # For laptop related

source= $UserConfigs/LaptopDisplay.conf # Laptop display related. You need to read the comment on this file

source= $UserConfigs/WindowRules.conf # all about Hyprland Window Rules and Layer Rules

source= $UserConfigs/UserDecorations.conf # Decorations config file

source= $UserConfigs/UserAnimations.conf # Animation config file

source= $UserConfigs/UserKeybinds.conf # Put your own keybinds here

source= $UserConfigs/UserSettings.conf # Main Hyprland Settings.

source= $UserConfigs/01-UserDefaults.conf # settings for User defaults apps

# nwg-displays
source= $HOME/.config/hypr/monitors.conf
source= $HOME/.config/hypr/workspaces.conf
 input {
    kb_layout = latam
    kb_variant =
    kb_model =
    kb_options =
    follow_mouse = 1
    touchpad {
        natural_scroll = yes
    }
    sensitivity = 0 # -1.0 - 1.0, 0 means no modification.
}

decoration {
    rounding = 10
    
    # Esto hace que la ventana de la terminal sea un poco más opaca
    active_opacity = 0.85
    inactive_opacity = 0.75

    blur {
        enabled = true
        size = 10           # Aumenta esto para desenfocar más el fondo
        passes = 4          # Más pases dan un efecto de "vidrio" más suave
        noise = 0.02        # Un poco de ruido ayuda a separar el texto
        contrast = 1.2      # Aumenta el contraste del fondo desenfocado
        brightness = 0.8    # Oscurece un poco el fondo para que el texto blanco resalte
    }
}
